sensor_info:
  # Topic
  sub_lidar1_topic: /hesai64/hesai/pandar
  sub_lidar2_topic: /velodyne_points
  sub_status_topic_: /tayo/decision/state
  pub_hesai_object_pcl_topic: /tayo/perception/object_pcl
  pub_hesai_globalfilter_pcl_topic: /tayo/perception/globalfilter_pcl
  pub_hesai_object_pt_topic: /tayo/perception/object_pt
  pub_hesai_object_polygon_topic: /tayo/perception/object_polygon
  pub_hesai_object_info_topic: /tayo/perception/object_info
  # Frame
  map_frame_id: map
  lidar_frame_id: pos
  sub_lidar_frame_id: pos
  # Sub LiDAR Transform info
  lidar_pose_x: 0.389838
  lidar_pose_y: -0.285417
  lidar_pose_z: -0.00960128
  lidar_ori_x:  -0.0010591
  lidar_ori_y:  0.00548515
  lidar_ori_z:  0.00958933
  lidar_ori_w:  0.999938

perception_param:
  map_info:
    map: "speedway"
    image_map: "/home/a/tayo_ws/src/tayo_perception/tayo_perception/map/everland.png"
    init_pose_x: 1000
    init_pose_y: 1000
    # map flag :0(no map), 1(2d map), 2(3d map)
    map_flag: 0
    final_lab: 10
  roi_filter:
    min_x: -10
    max_x: 60
    min_y: -10
    max_y: 10
    min_z: -5.0
    max_z: 0.5
  map_filter:
    min_thresh: 0.8
    max_thresh: 2.0
  ground_remover:
    grid_dim: 900
    per_cell: 0.18
    height_threshold: 0.3

    close_pt_min: -1.7
    close_pt_max: 0.3
  euclidean_cluster:
    range_cluster: 2.5
    min_cluster_size: 3
    max_cluster_size: 2500

