sensor_info:
  # Topic
  sub_lidar1_topic: /hesai64/hesai/pandar
  sub_lidar2_topic: /velodyne_points
  pub_hesai_object_pcl_topic: /tayo/perception/object_pcl
  pub_hesai_globalfilter_pcl_topic: /tayo/perception/globalfilter_pcl
  pub_hesai_object_pt_topic: /tayo/perception/object_pt
  pub_hesai_object_polygon_topic: /tayo/perception/object_polygon
  pub_hesai_object_info_topic: /tayo/perception/object_info
  # Frame
  map_frame_id: map
  lidar_frame_id: pos
  sub_lidar_frame_id: pos
  # Sub LiDAR Transform info
  lidar_pose_x: 0.393065
  lidar_pose_y: -0.276447
  lidar_pose_z: -0.0584303
  lidar_ori_x:  -0.00162189
  lidar_ori_y:  0.00390867
  lidar_ori_z:  -0.0227677
  lidar_ori_w:  0.999732

perception_param:
  map_info:
    map: "kiapi"
    image_map: "/home/a/tayo_ws/src/tayo_perception/tayo_perception/map/kiapi_general_v2.png"
    init_pose_x: 1210
    init_pose_y: 310
    # map flag :0(no map), 1(2d map), 2(3d map)
    map_flag: 1
    final_lab: 10

  roi_filter:
    min_x: -120
    max_x: 120
    min_y: -120
    max_y: 120
    min_z: -5.0
    max_z: 0.5
  map_filter:
    min_thresh: 0.2
    min_long_thresh: 1.5
    max_thresh: 2.0

    min_dist: 60
    max_dist: 200
  ground_remover:
    grid_dim: 900
    per_cell: 0.18
    height_threshold: 0.2

    close_pt_min: -1.7
    close_pt_max: -0.8
  noise_remover:
    remove_size: 4
  euclidean_cluster:
    range_cluster: 2.5
    min_cluster_size: 5
    max_cluster_size: 2500


