sensor_info:
  # Topic
  sub_lidar1_topic: /hesai/pandar
  sub_lidar2_topic: /velodyne_points
  sub_status_topic_: /tayo/decision/state
  pub_hesai_object_pcl_topic: /tayo/perception/object_pcl
  pub_hesai_globalfilter_pcl_topic: /tayo/perception/globalfilter_pcl
  pub_hesai_object_pt_topic: /tayo/perception/object_pt
  pub_hesai_object_polygon_topic: /tayo/perception/object_polygon
  pub_hesai_object_info_topic: /tayo/perception/object_info
  pub_id_topic: /tayo/perception/object_id
  # Frame
  map_frame_id: map
  lidar_frame_id: pos
  sub_lidar_frame_id: pos
  # Sub LiDAR Transform info
  lidar_pose_x: 0.389838
  lidar_pose_y: -0.285417
  lidar_pose_z: -0.00960128
  lidar_ori_x:  -0.0010591
  lidar_ori_y:  0.00548515
  lidar_ori_z:  0.00958933
  lidar_ori_w:  0.999938

perception_param:
  mode: "final"
  map_info:
    map: "speedway"
    image_map: "/home/a/tracking_ws/src/tayo_perception/tayo_perception/map/speedway_v4.png"
    stop_1_map: "/home/a/tracking_ws/src/tayo_perception/tayo_perception/map/stop_11_3d.png"
    stop_4_map: "/home/a/tracking_ws/src/tayo_perception/tayo_perception/map/stop_4_3d.png"
    init_pose_x: 0
    init_pose_y: 0
    # map flag :0(no map), 1(2d map), 2(3d map)
    map_flag: 2
    final_lab: 10
  roi_filter:
    min_x: -20
    max_x: 20
    min_y: -20
    max_y: 20
    min_z: -5.0
    max_z: 0.5
  map_filter:
    min_thresh: 0.5
    max_thresh: 2.0

    min_long_thresh: 0.5
    min_dist: 100
    max_dist: 200
  ground_remover:
    grid_dim: 900
    per_cell: 0.18
    height_threshold: 0.4

    close_pt_min: -1.7
    close_pt_max: 0.3
  noise_remover:
    remove_size: 2
  euclidean_cluster:
    range_cluster: 1.0
    min_cluster_size: 3
    max_cluster_size: 2500

